### PR TITLE
Protocol: 'any'

### PR DESCRIPTION
**Pull request by lgrahl**
Resolves #191

### CODE REVIEW

**Comment by quyunet** [comment]
hello, 

lgrahl, For the problem of lookup the whois via the 43 port in the sniproxy, and retured no results, and i found the access log from the sniproxy: http_access.log as below：
2016-09-16 17:14:38 [::ffff:120.76.28.88]:39300 -> [::]:43 -> NONE [] 7/7 bytes tx 10/20 bytes rx 0.000 seconds

can work correctly http_access.log as below：
2016-09-21 18:07:24 [::ffff:120.76.28.88]:36784 -> [::]:443 -> 109.234.109.34:443 [api.rrpproxy.net] 3668/3668 bytes tx 798/798 bytes rx 2.293 seconds

So may i know how to solve this problem? If need to fulfill the protocol module, then how to fulfill, would you kindly tell me the detailed way to fulfill?

Below is the former relative ticket:  https://github.com/dlundquist/sniproxy/issues/212

**Comment by lgrahl** [comment]
I'm sorry but I don't understand your question.

**Comment by quyunet** [comment]
do you know about WHOIS: https://whois.icann.org/en

lookup whois in the use of the 43 port in the sniproxy should be how to configure?

**Comment by quyunet** [comment]
you can help?

**Comment by lgrahl** [comment]
No, sorry. I don't want to be rude but I don't really understand your question. If you want to add a protocol to sniproxy, @dlundquist has already answered your question in the issue you've mentioned in your first posting.

**Pull request merged**
